import '../models/pet.dart';
import '../models/user_profile.dart';
import '../models/meetup.dart';
import '../models/passport_entry.dart';
import '../models/party_story.dart';

class MockData {
  static final currentUser = UserProfile(
    id: 'user_1',
    email: 'elijah@pawparty.com',
    displayName: 'Elijah',
    neighborhood: 'Maple Ridge',
    latitude: 40.7128,
    longitude: -74.0060,
    petIds: ['pet_1', 'pet_2'],
    childAges: ['6', '9'],
    hostCount: 2,
    attendCount: 5,
    hostRating: 4.8,
    guestRating: 4.9,
    isHostPassActive: false,
    createdAt: DateTime(2026, 1, 15),
    bio: 'Dog dad, pizza enthusiast, neighborhood connector',
  );

  static final userPets = [
    Pet(
      id: 'pet_1',
      ownerId: 'user_1',
      name: 'Biscuit',
      type: 'Dog',
      breed: 'Golden Retriever',
      gender: 'Male',
      size: 'Large (50-80 lbs)',
      ageYears: 3,
      ageMonths: 4,
      energyLevel: 0.8,
      socialComfort: 0.9,
      kidTolerance: 1.0,
      sizeTolerance: 0.7,
      playStyles: ['Chaser', 'Fetch Lover', 'Swimmer'],
      triggers: ['Cats'],
      bio: 'Loves everyone, especially kids. Will trade belly rubs for pizza crusts.',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 1, 15),
      meetupCount: 7,
      averageRating: 4.8,
    ),
    Pet(
      id: 'pet_2',
      ownerId: 'user_1',
      name: 'Mochi',
      type: 'Cat',
      breed: 'Scottish Fold',
      gender: 'Female',
      size: 'Small (10-25 lbs)',
      ageYears: 2,
      ageMonths: 0,
      energyLevel: 0.4,
      socialComfort: 0.3,
      kidTolerance: 0.5,
      sizeTolerance: 0.4,
      playStyles: ['Parallel Player', 'Explorer'],
      triggers: ['Loud noises', 'Large dogs'],
      bio: 'Prefers observing from high places. Selective about friends.',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 2, 1),
      meetupCount: 2,
      averageRating: 4.5,
    ),
  ];

  static final nearbyPets = [
    Pet(
      id: 'pet_3',
      ownerId: 'user_2',
      name: 'Duke',
      type: 'Dog',
      breed: 'German Shepherd',
      gender: 'Male',
      size: 'Large (50-80 lbs)',
      ageYears: 4,
      ageMonths: 0,
      energyLevel: 0.7,
      socialComfort: 0.6,
      kidTolerance: 0.8,
      sizeTolerance: 0.9,
      playStyles: ['Wrestler', 'Chaser', 'Tug Player'],
      triggers: ['Strangers'],
      bio: 'Loyal and protective. Takes a few minutes to warm up, then he\'s your best friend.',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 1, 20),
      meetupCount: 5,
      averageRating: 4.6,
    ),
    Pet(
      id: 'pet_4',
      ownerId: 'user_3',
      name: 'Poppy',
      type: 'Dog',
      breed: 'Cavalier King Charles',
      gender: 'Female',
      size: 'Small (10-25 lbs)',
      ageYears: 1,
      ageMonths: 8,
      energyLevel: 0.6,
      socialComfort: 0.95,
      kidTolerance: 1.0,
      sizeTolerance: 0.6,
      playStyles: ['Snuggler', 'Chaser', 'Parallel Player'],
      triggers: [],
      bio: 'Loves absolutely everyone. The ambassador dog of Maple Ridge!',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 2, 10),
      meetupCount: 12,
      averageRating: 5.0,
    ),
    Pet(
      id: 'pet_5',
      ownerId: 'user_4',
      name: 'Bear',
      type: 'Dog',
      breed: 'Bernese Mountain Dog',
      gender: 'Male',
      size: 'Extra Large (80+ lbs)',
      ageYears: 5,
      ageMonths: 0,
      energyLevel: 0.3,
      socialComfort: 0.7,
      kidTolerance: 0.9,
      sizeTolerance: 0.5,
      playStyles: ['Parallel Player', 'Snuggler'],
      triggers: ['Thunder/fireworks'],
      bio: 'Gentle giant who thinks he\'s a lap dog. Best at supervised napping.',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 1, 5),
      meetupCount: 8,
      averageRating: 4.9,
    ),
    Pet(
      id: 'pet_6',
      ownerId: 'user_5',
      name: 'Ziggy',
      type: 'Dog',
      breed: 'Border Collie Mix',
      gender: 'Male',
      size: 'Medium (25-50 lbs)',
      ageYears: 2,
      ageMonths: 3,
      energyLevel: 1.0,
      socialComfort: 0.8,
      kidTolerance: 0.7,
      sizeTolerance: 0.8,
      playStyles: ['Chaser', 'Fetch Lover', 'Explorer', 'Swimmer'],
      triggers: ['Leash reactive'],
      bio: 'Perpetual motion machine. Needs a friend who can keep up!',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 3, 1),
      meetupCount: 3,
      averageRating: 4.4,
    ),
    Pet(
      id: 'pet_7',
      ownerId: 'user_6',
      name: 'Luna',
      type: 'Dog',
      breed: 'Shiba Inu',
      gender: 'Female',
      size: 'Medium (25-50 lbs)',
      ageYears: 3,
      ageMonths: 6,
      energyLevel: 0.5,
      socialComfort: 0.4,
      kidTolerance: 0.6,
      sizeTolerance: 0.5,
      playStyles: ['Explorer', 'Parallel Player'],
      triggers: ['Small children', 'Loud noises'],
      bio: 'Independent thinker. Will judge you silently. Worth the effort.',
      isSpayedNeutered: true,
      isVaccinated: true,
      createdAt: DateTime(2026, 2, 20),
      meetupCount: 4,
      averageRating: 4.3,
    ),
  ];

  static final upcomingMeetups = [
    Meetup(
      id: 'meetup_1',
      hostId: 'user_3',
      hostName: 'Sarah M.',
      title: 'Sunday Puppy Bowl Hangout',
      description: 'Bring your pups for an afternoon of play! Big backyard, shaded patio, and of course... pizza!',
      theme: 'Puppy Bowl Sunday',
      dateTime: DateTime.now().add(const Duration(days: 3, hours: 5)),
      durationMinutes: 150,
      address: '42 Maple Lane, Maple Ridge',
      latitude: 40.7148,
      longitude: -74.0050,
      maxGuests: 4,
      invites: [
        MeetupInvite(
          guestId: 'user_1',
          guestName: 'Elijah',
          petIds: ['pet_1'],
          status: InviteStatus.accepted,
          sentAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        MeetupInvite(
          guestId: 'user_4',
          guestName: 'Marcus',
          petIds: ['pet_5'],
          status: InviteStatus.accepted,
          sentAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ],
      pizzaCommitment: const PizzaCommitment(
        willProvidePizza: true,
        willProvideDrinks: true,
        willAccommodateAllergies: true,
        acknowledgesHostDuty: true,
        pizzaPartner: "Joe's Pizzeria",
      ),
      hasYard: true,
      hasPool: false,
      kidFriendly: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Meetup(
      id: 'meetup_2',
      hostId: 'user_1',
      hostName: 'Elijah',
      title: 'Biscuit\'s Birthday Bash',
      description: 'Biscuit turns 4! Come celebrate with dog-safe cake, pizza for humans, and backyard fun.',
      theme: 'Birthday Bash',
      dateTime: DateTime.now().add(const Duration(days: 10, hours: 3)),
      durationMinutes: 180,
      address: '18 Oak Street, Maple Ridge',
      latitude: 40.7135,
      longitude: -74.0065,
      maxGuests: 6,
      invites: [
        MeetupInvite(
          guestId: 'user_3',
          guestName: 'Sarah M.',
          petIds: ['pet_4'],
          status: InviteStatus.accepted,
          sentAt: DateTime.now().subtract(const Duration(hours: 12)),
        ),
        MeetupInvite(
          guestId: 'user_5',
          guestName: 'Jake',
          petIds: ['pet_6'],
          status: InviteStatus.pending,
          sentAt: DateTime.now().subtract(const Duration(hours: 6)),
        ),
      ],
      pizzaCommitment: const PizzaCommitment(
        willProvidePizza: true,
        willProvideDrinks: true,
        willAccommodateAllergies: true,
        acknowledgesHostDuty: true,
      ),
      hasYard: true,
      hasPool: true,
      kidFriendly: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];

  static final passportEntries = [
    PassportEntry(
      id: 'pe_1',
      petId: 'pet_1',
      meetupId: 'meetup_old_1',
      meetupTitle: 'Summer Splash at the Hendersons',
      meetupTheme: 'Summer Splash',
      date: DateTime(2026, 3, 15),
      hostName: 'The Hendersons',
      metPetNames: ['Duke', 'Poppy', 'Bear'],
      rating: 5.0,
      behaviorNotes: 'Biscuit was the life of the party! Played fetch with the kids for an hour straight.',
      playOutcome: PlayOutcome.excellent,
      wasAnxious: false,
      playedWell: true,
      warmUpMinutes: 2,
    ),
    PassportEntry(
      id: 'pe_2',
      petId: 'pet_1',
      meetupId: 'meetup_old_2',
      meetupTitle: 'Casual Afternoon Hangout',
      meetupTheme: 'Casual Hangout',
      date: DateTime(2026, 3, 8),
      hostName: 'Sarah M.',
      metPetNames: ['Poppy'],
      rating: 4.5,
      behaviorNotes: 'Great one-on-one play session. Biscuit and Poppy are becoming regulars.',
      playOutcome: PlayOutcome.good,
      wasAnxious: false,
      playedWell: true,
      warmUpMinutes: 1,
    ),
    PassportEntry(
      id: 'pe_3',
      petId: 'pet_1',
      meetupId: 'meetup_old_3',
      meetupTitle: 'New Pet Welcome Party',
      meetupTheme: 'New Pet Welcome',
      date: DateTime(2026, 2, 22),
      hostName: 'Jake & Lisa',
      metPetNames: ['Ziggy'],
      rating: 3.5,
      behaviorNotes: 'Ziggy had a LOT of energy. Biscuit was a little overwhelmed at first but they figured it out.',
      playOutcome: PlayOutcome.okay,
      wasAnxious: false,
      playedWell: true,
      warmUpMinutes: 15,
    ),
    PassportEntry(
      id: 'pe_4',
      petId: 'pet_1',
      meetupId: 'meetup_old_4',
      meetupTitle: 'Valentine\'s Day party',
      meetupTheme: 'Holiday Howl',
      date: DateTime(2026, 2, 14),
      hostName: 'Marcus',
      metPetNames: ['Bear', 'Luna'],
      rating: 4.0,
      behaviorNotes: 'Bear and Biscuit napped together. Luna kept her distance but no issues.',
      playOutcome: PlayOutcome.good,
      wasAnxious: false,
      playedWell: true,
      warmUpMinutes: 5,
    ),
    PassportEntry(
      id: 'pe_5',
      petId: 'pet_2',
      meetupId: 'meetup_old_5',
      meetupTitle: 'Indoor Cat Meetup',
      meetupTheme: 'Casual Hangout',
      date: DateTime(2026, 3, 10),
      hostName: 'Amy',
      metPetNames: ['Whiskers', 'Mittens'],
      rating: 4.0,
      behaviorNotes: 'Mochi stayed on the bookshelf for 30 minutes then slowly came down. Progress!',
      playOutcome: PlayOutcome.okay,
      wasAnxious: true,
      playedWell: false,
      warmUpMinutes: 30,
    ),
  ];

  static final partyStories = [
    PartyStory(
      id: 'ps1',
      title: 'Sunday splash',
      caption: 'Kids + dogs + pizza = perfect afternoon.',
      createdAt: DateTime(2026, 3, 17),
      authorId: 'user_3',
      authorName: 'Sarah M.',
      meetupId: 'meetup_1',
    ),
    PartyStory(
      id: 'ps2',
      title: 'Birthday zoomies',
      caption: 'Biscuit got so many treats he crashed by 8pm.',
      createdAt: DateTime(2026, 3, 18),
      authorId: 'user_1',
      authorName: 'Elijah',
      meetupId: 'meetup_2',
    ),
  ];

  static double calculateCompatibility(Pet pet1, Pet pet2) {
    double score = 0;
    double maxScore = 0;

    // Energy level compatibility (closer = better)
    maxScore += 25;
    score += 25 * (1 - (pet1.energyLevel - pet2.energyLevel).abs());

    // Social comfort (both need to be comfortable enough)
    maxScore += 25;
    final minSocial = pet1.socialComfort < pet2.socialComfort
        ? pet1.socialComfort
        : pet2.socialComfort;
    score += 25 * minSocial;

    // Play style overlap
    maxScore += 25;
    final commonStyles = pet1.playStyles
        .where((s) => pet2.playStyles.contains(s))
        .length;
    final totalStyles = {...pet1.playStyles, ...pet2.playStyles}.length;
    if (totalStyles > 0) {
      score += 25 * (commonStyles / totalStyles);
    }

    // Size tolerance
    maxScore += 25;
    score += 25 * ((pet1.sizeTolerance + pet2.sizeTolerance) / 2);

    return (score / maxScore * 100).clamp(0, 100);
  }

  static UserProfile ownerProfile(String ownerId) {
    if (ownerId == currentUser.id) return currentUser;
    final o = _mockOwners[ownerId];
    if (o != null) return o;
    return UserProfile(
      id: ownerId,
      email: 'neighbor@pawparty.app',
      displayName: 'Pet parent',
      neighborhood: 'Nearby',
      petIds: const [],
      childAges: const [],
      hostCount: 0,
      attendCount: 0,
      hostRating: 0,
      guestRating: 0,
      isHostPassActive: false,
      createdAt: DateTime(2025, 1, 1),
    );
  }

  static final Map<String, UserProfile> _mockOwners = {
    'user_2': UserProfile(
      id: 'user_2',
      email: 'alex@example.com',
      displayName: 'Alex M.',
      neighborhood: 'Maple Ridge',
      latitude: 40.72,
      longitude: -74.01,
      petIds: const ['pet_3'],
      childAges: const ['4'],
      hostCount: 1,
      attendCount: 4,
      hostRating: 4.7,
      guestRating: 4.8,
      isHostPassActive: false,
      createdAt: DateTime(2025, 6, 1),
      bio: 'Trail runs with Duke every weekend.',
    ),
    'user_3': UserProfile(
      id: 'user_3',
      email: 'sarah@example.com',
      displayName: 'Sarah M.',
      neighborhood: 'Maple Ridge',
      latitude: 40.714,
      longitude: -74.008,
      petIds: const ['pet_4'],
      childAges: const ['2', '5'],
      hostCount: 3,
      attendCount: 8,
      hostRating: 4.9,
      guestRating: 5.0,
      isHostPassActive: false,
      createdAt: DateTime(2024, 3, 10),
      bio: 'Host of the neighborhood Puppy Bowl parties.',
    ),
    'user_4': UserProfile(
      id: 'user_4',
      email: 'jordan@example.com',
      displayName: 'Jordan K.',
      neighborhood: 'Cedar Hill',
      petIds: const ['pet_5'],
      childAges: const [],
      hostCount: 0,
      attendCount: 6,
      hostRating: 0,
      guestRating: 4.6,
      isHostPassActive: false,
      createdAt: DateTime(2025, 2, 1),
      bio: 'Bear and I love slow mornings on the porch.',
    ),
    'user_5': UserProfile(
      id: 'user_5',
      email: 'taylor@example.com',
      displayName: 'Taylor R.',
      neighborhood: 'Maple Ridge',
      petIds: const ['pet_6'],
      childAges: const ['8'],
      hostCount: 2,
      attendCount: 5,
      hostRating: 4.5,
      guestRating: 4.7,
      isHostPassActive: false,
      createdAt: DateTime(2025, 8, 15),
      bio: 'Agility class regular — Ziggy never quits.',
    ),
    'user_6': UserProfile(
      id: 'user_6',
      email: 'riley@example.com',
      displayName: 'Riley P.',
      neighborhood: 'Riverbend',
      petIds: const ['pet_7'],
      childAges: const [],
      hostCount: 0,
      attendCount: 3,
      hostRating: 0,
      guestRating: 4.4,
      isHostPassActive: false,
      createdAt: DateTime(2025, 11, 20),
      bio: 'Luna runs the household. I just pay rent.',
    ),
  };
}
