// File generated by FlutterFire CLI — replace placeholders by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then, the app runs without Firebase (media stays on local paths only).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Set to false until you run `flutterfire configure` (or paste real values).
class DefaultFirebaseOptions {
  static const String _placeholder = 'REPLACE_ME';

  /// True after `flutterfire configure` (or manual) replaces placeholders on this platform.
  static bool get isConfigured {
    final o = currentPlatform;
    return o.apiKey != _placeholder && o.projectId != _placeholder;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylKHK45EIvp3_0ZjJVE92pa4aHZYIv2k',
    appId: '1:1073924094679:web:237516c02bf5e4da1ece92',
    messagingSenderId: '1073924094679',
    projectId: 'pawparty-app',
    authDomain: 'pawparty-app.firebaseapp.com',
    storageBucket: 'pawparty-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JqkNxN7ACYkDiU6rDs79OYO4nh0YpXU',
    appId: '1:1073924094679:android:5ab2b340e05d85541ece92',
    messagingSenderId: '1073924094679',
    projectId: 'pawparty-app',
    storageBucket: 'pawparty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Vc4-VPz83l6fQ3a_fW0dFqnrtWfq0dw',
    appId: '1:1073924094679:ios:db3f0d980c7a0e731ece92',
    messagingSenderId: '1073924094679',
    projectId: 'pawparty-app',
    storageBucket: 'pawparty-app.firebasestorage.app',
    iosBundleId: 'com.pawparty.pawParty',
  );

}